
package AccesoAdmi;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import Conexion.ConexionMySQL;
import static Conexion.ConexionMySQL.conectar;
import Login.VentanaInicio;
import Usuario.Pago;
import org.mindrot.jbcrypt.BCrypt;
import java.sql.*;


public class AccesoAdmi extends javax.swing.JFrame {
     private boolean captchaVerificado = false;
     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccesoAdmi.class.getName());
    
    public AccesoAdmi() {
        initComponents();
    this.setSize(new Dimension(420, 530));
    ajustarImagenDeFondo(lblImagenFondo, "/imagen/FondoAcceso.png");

    lblImagenFondo.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            ajustarImagenDeFondo(lblImagenFondo, "/imagen/FondoAcceso.png");
        }
    });
    
        ConexionMySQL.configurar("root", "Olivera1234", "localhost", "3306", "bd");
        pnlCaptcha.setVisible(false);
        btnSesion.setEnabled(true);
    
    pnlCaptcha.setVisible(false);   // ✅ Ocultar CAPTCHA al inicio
    btnSesion.setEnabled(true);     // Activado al inicio (se desactiva al mostrar CAPTCHA)
    }
      
   public static boolean existeUsuario(String correo, String contraseñaPlano) {
        String sql = "SELECT contraseña FROM usuario WHERE correo = ?";
        try (Connection con = conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, correo);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String hashGuardado = rs.getString("contraseña");
                return BCrypt.checkpw(contraseñaPlano, hashGuardado);
            }
            return false;
        } catch (SQLException e) {
            System.out.println("Error al buscar: " + e.getMessage());
            return false;
        }
    }

    public static boolean numeroRol(String correo, int rol) {
        String sql = "SELECT * FROM usuario WHERE correo = ? AND id_Rol = ?";
        try (Connection con = conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, correo);
            ps.setInt(2, rol);
            ResultSet rs = ps.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            System.out.println("Error al buscar: " + e.getMessage());
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAcceso = new javax.swing.JPanel();
        txtMail = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btnSesion = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        LogoLBL = new javax.swing.JLabel();
        pnlCaptcha = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        txtCaptcha = new javax.swing.JTextField();
        captchaPanel = new CaptchaPanel();
        lblEmpresa = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAcceso.setPreferredSize(new java.awt.Dimension(350, 500));
        pnlAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMailKeyPressed(evt);
            }
        });
        pnlAcceso.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 205, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        pnlAcceso.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 205, -1));

        btnSesion.setBackground(new java.awt.Color(51, 153, 255));
        btnSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnSesion.setText("Iniciar Sesión");
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        pnlAcceso.add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 36));
        pnlAcceso.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        pnlAcceso.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 39));

        LogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Joystickland_logo_128x128.png"))); // NOI18N
        pnlAcceso.add(LogoLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        pnlCaptcha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/actualizar.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        pnlCaptcha.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 49, 30));

        btnVerificar.setText("verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        pnlCaptcha.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 32));
        pnlCaptcha.add(txtCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 140, 30));

        javax.swing.GroupLayout captchaPanelLayout = new javax.swing.GroupLayout(captchaPanel);
        captchaPanel.setLayout(captchaPanelLayout);
        captchaPanelLayout.setHorizontalGroup(
            captchaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        captchaPanelLayout.setVerticalGroup(
            captchaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnlCaptcha.add(captchaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        pnlAcceso.add(pnlCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 310, 120));

        lblEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpresa.setText("© JoysticklandStore");
        pnlAcceso.add(lblEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FondoAcceso.png"))); // NOI18N
        pnlAcceso.add(lblImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        String correo = txtMail.getText().trim();
        String password = new String(txt_password.getPassword()).trim();
        boolean hayError = false;

        txtMail.setBorder(javax.swing.UIManager.getBorder("TextField.border"));
        txt_password.setBorder(javax.swing.UIManager.getBorder("PasswordField.border"));

        if (correo.isEmpty()) {
            txtMail.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
            JOptionPane.showMessageDialog(this, "El campo de correo está vacío.");
            txtMail.requestFocus();
            hayError = true;
        } else if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            txtMail.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
            JOptionPane.showMessageDialog(this, "El correo no es válido. Debe contener '@' y un dominio.");
            txtMail.requestFocus();
            hayError = true;
        }

        if (password.isEmpty()) {
            txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
            JOptionPane.showMessageDialog(this, "El campo de contraseña está vacío.");
            txt_password.requestFocus();
            hayError = true;
        } else if (password.length() < 6) {
            txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
            txt_password.requestFocus();
            hayError = true;
        }

        if (hayError) return;

        if (!captchaVerificado) {
            if (!pnlCaptcha.isVisible()) {
                pnlCaptcha.setVisible(true);
                captchaPanel.generarCaptcha();
                captchaPanel.repaint();
                txtCaptcha.setText("");
                btnSesion.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Verifica el CAPTCHA para continuar.");
            } else {
                JOptionPane.showMessageDialog(this, "Debes verificar el CAPTCHA antes de iniciar sesión.");
            }
            return;
        }

        if (ConexionMySQL.conectar() != null) {
            if (existeUsuario(correo, password)) {
                JOptionPane.showMessageDialog(this, "✅ Inicio de sesión exitoso.");

                if (numeroRol(correo, 1)) {
                    VentanaInicio ventana = new VentanaInicio();
                    ventana.setVisible(true);
                    ventana.setLocationRelativeTo(null);
                    this.dispose();
                } else if (numeroRol(correo, 2)) {
                    Pago pago = new Pago();
                    pago.setVisible(true);
                    pago.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Rol no reconocido.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "❌ Credenciales incorrectas.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.");
        }

    }//GEN-LAST:event_btnSesionActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed

    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txtMailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailKeyPressed

    }//GEN-LAST:event_txtMailKeyPressed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    captchaPanel.generarCaptcha();
    txtCaptcha.setText("");
    captchaVerificado = false;
    btnSesion.setEnabled(false); // 🔒 Se bloquea hasta nuevo verificado
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        String captchaIngresado = txtCaptcha.getText().trim();
        String captchaReal = captchaPanel.getCodigo();

        if (captchaIngresado.equalsIgnoreCase(captchaReal)) {
            captchaVerificado = true;
            btnSesion.setEnabled(true);
            JOptionPane.showMessageDialog(this, "✅ CAPTCHA verificado correctamente.");
        } else {
            captchaVerificado = false;
            btnSesion.setEnabled(false);
            JOptionPane.showMessageDialog(this, "❌ CAPTCHA incorrecto. Inténtalo de nuevo.");
        }

    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccesoAdmi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLBL;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSesion;
    private javax.swing.JButton btnVerificar;
    private CaptchaPanel captchaPanel;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel pnlAcceso;
    private javax.swing.JPanel pnlCaptcha;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JTextField txtMail;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables


    private void ajustarImagenDeFondo(JLabel label, String ruta) {
    java.net.URL url = getClass().getResource(ruta);
    if (url != null) {
        ImageIcon originalIcon = new ImageIcon(url);
        Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            label.getWidth(),
            label.getHeight(),
            Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(imagenEscalada));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
    } else {
        System.err.println("⚠ Imagen no encontrada en: " + ruta);
    }
  }
}
