/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AccesoAdmi;

import java.awt.Color;
import javax.swing.JOptionPane;
import Conexion.ConexionMySQL;
import static Conexion.ConexionMySQL.conectar;
import Login.VentanaInicio;
import Usuario.Pago;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import org.mindrot.jbcrypt.BCrypt;
import java.sql.*;
/**
 *
 * @author felix
 */
public class Login extends javax.swing.JFrame {
    ConexionMySQL con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        ConexionMySQL con=new ConexionMySQL();
        ConexionMySQL.configurar("root", "Olivera1234", "localhost", "3306", "bd");
        txtC.setText("Correo");
        txtC.setForeground(Color.LIGHT_GRAY);
        txtCo.setText("Contraseña");
        txtCo.setForeground(Color.LIGHT_GRAY);
        
        txtC.addFocusListener(new FocusAdapter() {
    @Override
    public void focusGained(FocusEvent e) {
        if (txtC.getText().equals("Correo")) {
            txtC.setText("");
            txtC.setForeground(Color.BLACK);
        }
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (txtC.getText().trim().isEmpty()) {
            txtC.setText("Correo");
            txtC.setForeground(Color.lightGray);
        }
    }
});

// Focus para CONTRASEÑA (si usas JTextField)
txtCo.addFocusListener(new FocusAdapter() {
    @Override
    public void focusGained(FocusEvent e) {
        if (txtCo.getText().equals("Contraseña")) {
            txtCo.setText("");
            txtCo.setForeground(Color.BLACK);
        }
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (txtCo.getText().trim().isEmpty()) {
            txtCo.setText("Contraseña");
            txtCo.setForeground(Color.lightGray);
        }
    }
});

        
    }
    
    public static boolean existeUsuario(String correo, String contraseñaPlano) {
    
    String sql = "SELECT contraseña FROM usuario WHERE correo = ?";
    
    try (Connection con = conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        ps.setString(1, correo);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            String hashGuardado = rs.getString("contraseña");   // el hash bcrypt
            // comparamos la contraseña con la encriptada
            return BCrypt.checkpw(contraseñaPlano, hashGuardado);
        }
        return false;               // no existe el correo en la BD
    } catch (SQLException e) {
        System.out.println("Error al buscar: " + e.getMessage());
        return false;
    }
}
    
    public static boolean numeroRol(String correo, int rol) {
    String sql = "SELECT * FROM usuario WHERE correo = ? AND id_Rol = ?";
    try {
        Connection con = conectar();
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, correo);
        ps.setInt(2, rol);
        ResultSet rs = ps.executeQuery();
        return rs.next(); // true si existe una fila que cumple
    } catch (SQLException e) {
        System.out.println("Error al buscar: " + e.getMessage());
        return false;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtC.setText("Correo");
        txtC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCMouseClicked(evt);
            }
        });
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.41.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.52.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.72.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.62.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.81.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.94.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.91.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        txtCo.setText("Contraseña");
        txtCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCoMouseClicked(evt);
            }
        });
        txtCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo4.12.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, 100));

        lblA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 260, 20));

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, 260));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.96.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 450, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.21.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 550, 410));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo3.21.png"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        con.conectar();
       
        
        if(con.estaConectado()==true){
            
            if(existeUsuario(txtC.getText(), txtCo.getText())){
                JOptionPane.showMessageDialog(null, "Bienvenido");
                
                if(numeroRol(txtC.getText(),1)){
                VentanaInicio i=new VentanaInicio();
                i.setVisible(true);
                i.setLocationRelativeTo(null);
                
                this.dispose();
                }
                if(numeroRol(txtC.getText(),2)){
               Pago v=new Pago();
                v.setVisible(true);
               
                this.dispose();
                }
                           
            }else{
            lblA.setText("Ingresa tus credenciales correctamente.");
            lblA.setForeground(Color.red);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error al establecer conexion.");
        }
        
      
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoActionPerformed

    private void txtCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCoMouseClicked
        // TODO add your handling code here:
        txtCo.setText("");
        lblA.setText("");
    }//GEN-LAST:event_txtCoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblA;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtCo;
    // End of variables declaration//GEN-END:variables
}
