/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import Conexion.ConexionMySQL;
import static Conexion.ConexionMySQL.conectar;
import elementos.Correo;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.mail.MessagingException;
import javax.swing.JDialog;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author felix
 */
public class EdiitarUs extends javax.swing.JFrame {
    Map<String, Object> datos;
    private int idUsuario;
    private String correoActual;
    private String contraseñaActual;
    private String nombreActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EdiitarUs.class.getName());

    /**
     * Creates new form EdiitarUs
     */
    public EdiitarUs() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        datos = new HashMap<>();
        ConexionMySQL.configurar("root", "Olivera1234", "localhost", "3306", "bd");
        this.Cargarroles();
        
    }
    
    public  void cargarDatos(int idUsuario, String correo, String contraseña, String nombre){
        this.idUsuario = idUsuario;
        this.correoActual = correo;
        this.contraseñaActual = contraseña;
        this.nombreActual=nombre;
    }
    
    
    private void Cargarroles(){
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        ResultSet rs = ConexionMySQL.listarTodo("rol");

    try {
        while (rs != null && rs.next()) {
            modelo.addElement(rs.getString("rol")); // Solo agrega el nombre del rol
        }
        Rol.setModel(modelo); 
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar productos: " + e.getMessage());
    }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        Rol = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblM = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Editor de usuarios:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 12, 165, -1));

        jLabel2.setText("Nuevo  correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, 87, -1));

        jLabel3.setText("Nueva contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 100, 110, -1));

        jLabel4.setText("Nuevo Rol:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 222, 68, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 49, 201, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 95, 201, -1));

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolActionPerformed(evt);
            }
        });
        getContentPane().add(Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 214, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Guardar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 282, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 282, -1, -1));
        getContentPane().add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 331, 278, 24));

        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 157, 68, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 152, 201, -1));

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RolActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // Verificar si el ID es válido
    if (idUsuario == -1) {
        JOptionPane.showMessageDialog(null, "Selecciona primero un usuario para editar.");
        return;
    }

    String nuevoCorreo = t1.getText().trim();
    String nuevaContraseña = t2.getText().trim();
    String nuevoNombre = t3.getText().trim(); // Nuevo campo para el nombre
    int nuevoRol = Rol.getSelectedIndex() + 1;

    String correoFinal;
    String contraseñaFinal;
    String nombreFinal;

    // Validación del nuevo correo
    if (nuevoCorreo.isEmpty()) {
        int opcionCorreo = JOptionPane.showConfirmDialog(
            null,
            "No ingresaste un nuevo correo. Se mantendrá el actual.\n¿Deseas continuar?",
            "Confirmar actualización",
            JOptionPane.YES_NO_OPTION
        );
        if (opcionCorreo != JOptionPane.YES_OPTION) return;
        correoFinal = correoActual;
    } else {
        correoFinal = nuevoCorreo;
    }

    // Validación de nueva contraseña
    if (nuevaContraseña.isEmpty()) {
        int opcionContraseña = JOptionPane.showConfirmDialog(
            null,
            "No ingresaste una nueva contraseña. Se mantendrá la actual.\n¿Deseas continuar?",
            "Confirmar actualización",
            JOptionPane.YES_NO_OPTION
        );
        if (opcionContraseña != JOptionPane.YES_OPTION) return;
        contraseñaFinal = contraseñaActual; // Ya está encriptada
    } else {
        contraseñaFinal = BCrypt.hashpw(nuevaContraseña, BCrypt.gensalt());
    }

    // Validación del nuevo nombre
    if (nuevoNombre.isEmpty()) {
        int opcionNombre = JOptionPane.showConfirmDialog(
            null,
            "No ingresaste un nuevo nombre. Se mantendrá el actual.\n¿Deseas continuar?",
            "Confirmar actualización",
            JOptionPane.YES_NO_OPTION
        );
        if (opcionNombre != JOptionPane.YES_OPTION) return;
        nombreFinal = nombreActual;
    } else {
        nombreFinal = nuevoNombre;
    }

    // Ejecutar actualización en la base de datos
    try {
        Connection con = conectar();
        String sql = "UPDATE usuario SET nombre = ?, correo = ?, contraseña = ?, id_Rol = ? WHERE id = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, nombreFinal);
        ps.setString(2, correoFinal);
        ps.setString(3, contraseñaFinal);
        ps.setInt(4, nuevoRol);
        ps.setInt(5, idUsuario);
        ps.executeUpdate();

        lblM.setText("Se actualizó correctamente el usuario");
        lblM.setForeground(Color.black);

        ps.close();
        con.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EdiitarUs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Rol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblM;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
