/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Conexion.ConexionMySQL;
import static Conexion.ConexionMySQL.conectar;
import elementos.Correo;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.mail.MessagingException;
import javax.swing.JDialog;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;


/**
 *
 * @author felix
 */
public class Registro extends javax.swing.JFrame {
     Map<String, Object> datos;
     String remitente;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    /**
     * Creates new form Regustro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        datos = new HashMap<>();
        remitente="";
        ConexionMySQL.configurar("root", "Olivera1234", "localhost", "3306", "bd");
        this.Cargarroles();
    }
    
    private void Cargarroles(){
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        ResultSet rs = ConexionMySQL.listarTodo("rol");

    try {
        while (rs != null && rs.next()) {
            modelo.addElement(rs.getString("rol")); // Solo agrega el nombre del rol
        }
        Rol.setModel(modelo); 
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar productos: " + e.getMessage());
    }
    }
    
    public static boolean existeCorreo(String correo) {
    String sql = "SELECT 1 FROM usuario WHERE correo = ? LIMIT 1";
    try (Connection con = conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        ps.setString(1, correo);
        try (ResultSet rs = ps.executeQuery()) {
            return rs.next(); // Devuelve true si hay al menos un resultado
        }
    } catch (SQLException e) {
        System.out.println("Error al verificar correo: " + e.getMessage());
        return false; // En caso de error, asumimos que no existe
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtContrApli1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblM3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblM = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Rol = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        P.setAlwaysOnTop(true);
        P.setModal(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Contraseña de aplicaciones de Gmail");

        jLabel11.setText("Ingresa la contraseña de plicacion del gmail del nuevo gerente.");

        jLabel12.setText("Si no sabe cual es busque ayuda.");

        txtContrApli1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContrApli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrApli1ActionPerformed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Asegurese de ingresarlo correctamente.");

        lblM3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLayout = new javax.swing.GroupLayout(P.getContentPane());
        P.getContentPane().setLayout(PLayout);
        PLayout.setHorizontalGroup(
            PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLayout.createSequentialGroup()
                .addGroup(PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblM3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)))
                    .addGroup(PLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContrApli1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton3)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        PLayout.setVerticalGroup(
            PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(txtContrApli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblM3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido al registro de usuarios.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 6, 287, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 126, 48, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Confirmar contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 214, -1, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 124, 201, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 168, 201, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 212, 201, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 325, -1, -1));
        getContentPane().add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 384, 334, 28));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Rol:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 265, -1, -1));

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolActionPerformed(evt);
            }
        });
        getContentPane().add(Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 260, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 325, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre completo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 82, -1, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 80, 201, -1));

        jLabel7.setBackground(new java.awt.Color(153, 204, 255));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Correo o=new Correo();
         
        if(!t1.getText().equals("") && !t2.getText().equals("") && !t3.getText().equals("")){
            if(t2.getText().equals(t3.getText())){
                if(existeCorreo(t1.getText())==false){
                
                try {
                    
                    int rol = Rol.getSelectedIndex() + 1;

                    String correo = t1.getText();
                    String contraseñaPlano = t2.getText(); // Contraseña escrita por el usuario
                    String nombre=t4.getText();
                    String contraseñaEncriptada = BCrypt.hashpw(contraseñaPlano, BCrypt.gensalt());

                    datos.put("correo", correo);
                    datos.put("nombre", nombre);
                    datos.put("contraseña", contraseñaEncriptada); // Guardamos la contraseña encriptada
                    datos.put("id_Rol", rol);

                    ConexionMySQL.insertar("usuario", datos);

                    lblM.setText("Se agregó correctamente el usuario");
                    lblM.setForeground(Color.black);
                    
                                     
                    o.setDestinatario(t1.getText());
                    o.setRemitente("joysticklandtoystore@gmail.com", "g b z i u u t z c f a d p k q r");
                    o.agregarArchivo("C:/Users/felix/Documents/Bienvenida.pdf");
                    o.setContenido("Hola", "Prueba");
                    o.enviarCorreo();
                } catch (MessagingException ex) {
                    System.getLogger(Registro.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
              
                }else{
                    lblM.setText("El correo que intenta ingresar ya existe.");
                    lblM.setForeground(Color.red); 
                }
                
                
            }else{
            lblM.setText("Favor de ingresar la misma contraseña en el campo..");
            lblM.setForeground(Color.red); 
            }
            
        }else{
            lblM.setText("Favor de rellenar todos los campos.");
            lblM.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RolActionPerformed

    private void txtContrApli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrApli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrApli1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        datos.put("contraseña_aplicacion", txtContrApli1.getText());
        P.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog P;
    private javax.swing.JComboBox<String> Rol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblM3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField txtContrApli1;
    // End of variables declaration//GEN-END:variables
}
