/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Login.VentanaProdcto;
import Login.VentanaUs;
import Login.VentanaVent;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author HP
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());


    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
            // Ajuste inicial de fondo
    ajustarImagenDeFondo(lblImagenInicio, "/imagen/FondoInicio.png");

    // Ajuste dinámico al cambiar el tamaño
    lblImagenInicio.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            ajustarImagenDeFondo(lblImagenInicio, "/imagen/FondoInicio.png");
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensaje1 = new javax.swing.JLabel();
        lblMensaje2 = new javax.swing.JLabel();
        btnAdministrador = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPuntoVenta = new javax.swing.JButton();
        lblAdministrador = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        lblImagenInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensaje1.setBackground(new java.awt.Color(0, 0, 255));
        lblMensaje1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        lblMensaje1.setText("¡Bienvenido/a a JOYSTICKLAND! ");
        getContentPane().add(lblMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        lblMensaje2.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        lblMensaje2.setText("Seleccione una opcion para comenzar");
        getContentPane().add(lblMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 81, -1, -1));

        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/gestion-de-base-de-datos.png"))); // NOI18N
        btnAdministrador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 137, 90, -1));

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/distribucion.png"))); // NOI18N
        btnProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 137, 90, -1));

        btnPuntoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/punto-de-venta.png"))); // NOI18N
        btnPuntoVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuntoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 136, 90, -1));

        lblAdministrador.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        lblAdministrador.setText("Administrador");
        getContentPane().add(lblAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblProductos.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        lblProductos.setText("Productos");
        getContentPane().add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        lblVentas.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        lblVentas.setText("Ventas");
        getContentPane().add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));
        getContentPane().add(lblImagenInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        // TODO add your handling code here:
        VentanaUs v=new VentanaUs();
        v.setVisible(true);
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        VentanaProdcto a=new VentanaProdcto();
        a.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoVentaActionPerformed
        // TODO add your handling code here:
        VentanaVent u=new VentanaVent();
        u.setVisible(true);
    }//GEN-LAST:event_btnPuntoVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnPuntoVenta;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblImagenInicio;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblMensaje2;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblVentas;
    // End of variables declaration//GEN-END:variables

private void ajustarImagenDeFondo(javax.swing.JLabel label, String ruta) {
    java.net.URL imgURL = getClass().getResource(ruta);
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image imagen = icon.getImage().getScaledInstance(
            label.getWidth(), label.getHeight(), java.awt.Image.SCALE_SMOOTH);
        label.setIcon(new javax.swing.ImageIcon(imagen));
    } else {
        System.err.println("No se pudo encontrar la imagen: " + ruta);
    }
}

    private void addHoverEffect(JButton button) {
        Color original = new Color(204, 255, 255);
        Color hover = new Color(153, 255, 255);

        button.setBackground(original);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(original);
            }
        });
    }
// Clase extra: RoundedButton.java
class RoundedButton extends JButton {

    private final int arcWidth = 30;
    private final int arcHeight = 30;

    public RoundedButton(Icon icon) {
        super(icon);
        setOpaque(false);
        setContentAreaFilled(false);
        setFocusPainted(false);
        setBorderPainted(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), arcWidth, arcHeight);
        g2.dispose();
        super.paintComponent(g);
    }

    @Override
    public void setContentAreaFilled(boolean b) {
        // Ignorado para mantener diseño personalizado
    }
}

}
